### ISSUE TITLE
DynamoDB 입력 방식?

### ISSUE THREAD

**Issue by rbrbrb7290** [mrfourfour/ticket-server#8]
PK + SK 로 테이블 생성

1. PK에 변수를 붙여 넣을것인가
2. 동일한 PK를 넣고 SK에 변수를 넣을 것인가 (이걸로 하기로)

3. 변수를 직접작성할지  uuid생성을 할지 (UUID쓰기로)

**Comment by aerain** [comment]
답은 동일 PK와 UUID를 사용한 SK
